import os
import sys
import traceback
import concurrent.futures

# Ensure Python can find local modules when imported from app.py/server.py
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from cut_keyframe import extract_keyframes
from utils.embedding_utils import generate_session_embeddings
from eva02_retrieval_trake import EVA02ImageRetrieval

class JobManager:
    def __init__(self, max_workers=2):
        self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=max_workers)
        # In-memory dictionary to hold statuses. 
        # For production, replace this with Redis/DB queries.
        self.session_status = {}

    def get_status(self, session_id):
        """Retrieve the current progress and status of a session."""
        return self.session_status.get(session_id, {
            "status": "NOT_FOUND",
            "progress": 0,
            "message": "Session not found or hasn't started."
        })

    def update_status(self, session_id, status=None, progress=None, message=None):
        """Thread-safe state update."""
        if session_id not in self.session_status:
            self.session_status[session_id] = {
                "status": "PENDING",
                "progress": 0,
                "message": "Initializing..."
            }
        
        state = self.session_status[session_id]
        if status is not None:
            state["status"] = status
        if progress is not None:
            state["progress"] = progress
        if message is not None:
            state["message"] = message

    def submit_video_job(self, session_id, raw_video_path, dirs):
        """
        Public method to submit a job to the background thread executor.
        `dirs` is the dictionary generated by `initialize_user_workspace()`.
        """
        self.update_status(session_id, status="PENDING", message="Job submitted to queue.")
        self.executor.submit(self._process_video_task, session_id, raw_video_path, dirs)

    def _process_video_task(self, session_id, raw_video_path, dirs):
        """
        The orchestrator sequence running in the background thread.
        1. Extract Keyframes (0% -> 20%)
        2. Generate Embeddings (20% -> 95%)
        3. Build FAISS & Init Retrieval (95% -> 100%)
        """
        try:
            # --- Milstone 1: Extract Keyframes ---
            self.update_status(session_id, status="EXTRACTING_FRAMES", progress=0, message="Starting keyframe extraction...")
            
            def keyframe_callback(current, total):
                # Map 0-100% of keyframes to 0-20% overall
                if total > 0:
                    pct = int((current / total) * 20.0)
                    self.update_status(session_id, progress=pct, message=f"Extracted {current}/{total} frames.")

            extract_keyframes(
                video_path=raw_video_path, 
                output_dir=dirs["root"], 
                threshold=0.95,
                progress_callback=keyframe_callback
            )

            # --- Milestone 2: Generate Embeddings ---
            self.update_status(session_id, status="EMBEDDING", progress=20, message="Generating EVA02 embeddings...")
            
            def embedding_callback(current, total):
                # Map 0-100% of embeddings to 20-95% overall
                if total > 0:
                    pct = 20 + int((current / total) * 75.0)
                    self.update_status(session_id, progress=pct, message=f"Embedded {current}/{total} images.")

            generate_session_embeddings(
                session_dir=dirs["root"], 
                progress_callback=embedding_callback
            )

            # --- Milestone 3: Build FAISS Index ---
            self.update_status(session_id, status="BUILDING_INDEX", progress=95, message="Building FAISS Index database...")
            
            retrieval = EVA02ImageRetrieval(
                embedding_dir=dirs["embeddings"],
                keyframes_dir=dirs["keyframes"],
                db_path=os.path.join(dirs["db"], "faiss_db.pkl"),
                map_keyframes_dir=dirs["map_keyframes"]
            )
            # Force save the database explicitly here so it is available even without searches
            retrieval.vector_db.save_database()

            # --- Finalize ---
            self.update_status(session_id, status="DONE", progress=100, message="Video processed successfully.")

        except Exception as e:
            err_msg = str(e)
            print(f"[{session_id}] PIPELINE EXCEPTION: \n{traceback.format_exc()}")
            self.update_status(session_id, status="FAILED", progress=0, message=f"Video processing failed: {err_msg}")

# Create a global instance so the Flask App can import and use the same worker pool
pipeline_manager = JobManager(max_workers=2)
